#include "systemc.h"
#include "rfsm.h"
#include "inp_H.h"
#include "a1.h"
#include "a2.h"

int sc_main(int argc, char *argv[])
{
  sc_signal<bool> H;
  sc_signal<bool> e;
  sc_signal<int> a1_state;
  sc_signal<int> a2_state;
  sc_trace_file *trace_file;
  trace_file = sc_create_vcd_trace_file ("main");
  sc_write_comment(trace_file, "Generated by RFSM v1.7.0 from model main.fsm");
  sc_trace(trace_file, H, "H");
  sc_trace(trace_file, e, "e");
  sc_trace(trace_file, a1_state, "a1_state");
  sc_trace(trace_file, a2_state, "a2_state");

  Inp_H Inp_H("Inp_H");
  Inp_H(H);

  A1 a1("a1");
  a1(H,e,a1_state);
  A2 a2("a2");
  a2(H,e,a2_state);

  sc_start(120, SC_NS);

  sc_close_vcd_trace_file (trace_file);

  return EXIT_SUCCESS;
}
