#!/bin/bash

for target in dot.run sim.run ctask systemc.run vhdl.run
do
    ./do_tests $target simple
    for i in szdints szvars
    do
         ./do_tests --compiler /Users/jserot/Dev/ml/rfsm/_build/default/src/guests/exp/$i/bin/rfsmc.bc $target simple
    done

    ./do_tests $target szdints
    for i in szvars
    do
         ./do_tests --compiler /Users/jserot/Dev/ml/rfsm/_build/default/src/guests/exp/$i/bin/rfsmc.bc $target simple
    done

    ./do_tests $target szvars

done
