#!/bin/bash

RFSMC=/Users/jserot/Dev/ml/rfsm/_build/default/src/guests/std/bin/rfsmc.exe

GUARD_TESTS="x x+1 x+y x+y*2-a[z+1]"
ACTION_TESTS="x:=1 x:=y+1 t[i]:=i+1 ev"
SVAL_TESTS="x=1 x=1+1"

for i in sval_ok*.fsp sval_err*.fsp action_ok*.fsp action_err*.fsp
do
   echo "Checking $i... "
   $RFSMC -check_fragment $i
done
