#!/bin/bash
if [ "$#" -eq 3 ]; then
    cat $2 > $3
    echo "" >> $3
    echo "let spec = [" >> $3
    awk -F ";" '{ printf("\"%s\", %s %s, \"%s\";\n", $3, $4, $5, $6) }' < $1 >> $3
    echo "];" >> $3
else
    echo "usage: $0 spec_file ifile ofile"
fi
