APP=main
DOT_OPTS=#-dot_fsm_models
SIM_OPTS=
SYSTEMC_OPTS=-sc_time_unit "SC_NS" -stop_time 300 -sc_trace
VHDL_OPTS=-vhdl_time_unit "ns" -vhdl_numeric_std -stop_time 300 -vhdl_trace

include ../../../../lib/etc/Makefile.app
