GHDL=ghdl
GHDLOPTS=-P/Users/jserot/Dev/ml/rfsm/working/examples/lib/vhdl
GTKWAVE=PATH=/Applications/gtkwave.app/Contents/MacOS:$(PATH) gtkwave-bin

all: run

tb: syracuse.vhd tb.vhd
	$(GHDL) -a $(GHDLOPTS) syracuse.vhd
	$(GHDL) -a $(GHDLOPTS) tb.vhd
	$(GHDL) -e $(GHDLOPTS) tb

run: tb
	$(GHDL) -r $(GHDLOPTS) tb --stop-time=200ns --vcd=tb.vcd

sim: run
	$(GTKWAVE) -f tb.vcd -a tb.sav > /tmp/gtkwave.log 2>&1; echo $$?

clean:
	\rm -f work*.cf
	\rm -f *.o
	\rm -f tb
	\rm -f tb.vcd

clobber: clean
	\rm -f *~
	\rm -rf html
