#!/bin/bash

DO_TEST="./do_test"
SUBDIRS="core simple szdints szvars typarams"

while : ; do
  case "$1" in
    "") break;;
    --compiler)
        DO_TEST="$DO_TEST --compiler $2"; shift;;
    -help|--help)
        cat <<EOF
Usage: do_tests [options] kind subdir
where
options: [defaults in brackets after descriptions]
  --compiler path         path to the rfsmc compiler [default: $RFSMC]
  --show                  launch DOT or VCD viewer after running the test [default: no]
  --help                  print this message
kind=makefile|dot.run|dot|sim|ctask|systemc.code|systemc.run|systemc|systemc.sim|vhdl.code|vhdl.run|vhdl|vhdl.sim
subdir=core|simple|...|all
EOF
	exit 0;;
    *) break;;
  esac
  shift
done

#echo "DO_TEST=$DO_TEST 1=$1 2=$2"

run ()
{
nt=0
ns=0
for i in $2/{single,multi}/[a-z]*
do
  (( nt = nt + 1 ))
  $DO_TEST $1 $i
  (( ns = ns + $? ))
done
echo "***" $ns"/"$nt "test(s) OK"
}

case $2 in
    all) 
        for i in $SUBDIRS
        do
            run $1 $i
        done;;
    *)
        run $1 $2;;
esac
