#!/bin/bash
# A script for automated testing 

function try_make
{
make test
case $? in
0) echo "OK";;
*) echo "FAILED";;
esac
}

TMP=/tmp/do_test.out

echo -n "Testing in $1... "
(cd $1; if [ -e Makefile ]; then make clean > $TMP 2>&1; fi)
(cd $1; try_make $1 && make clean) > $TMP 2>&1
grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
grep "OK" $TMP >/dev/null && exit 1
exit 0
