#!/bin/bash
# A script for automated testing 

try_make () 
{
make $1
case $? in
0) echo "OK";;
*) echo "FAILED";;
esac
}

TMP=/tmp/do_test.out

if [ "$#" -eq 2 ]; then
    echo -n "Making $1 in $2... "
    (cd $2; if [ -e Makefile ]; then make clean > $TMP 2>&1; fi)
    (cd $2; try_make $1 && make clean) > $TMP 2>&1
    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
    grep "OK" $TMP >/dev/null && exit 1
    exit 0
else
    echo "usage: $0 (dot|sim|systemc|vhdl|all) dir"
fi
