#!/bin/bash

# A script for automatically running examples

RUN_TEST="../etc/bin/run_test"
SUBDIRS="std"

while : ; do
  case "$1" in
    "") break;;
    -makefile)
        RUN_TEST="$RUN_TEST -makefile";;
    -show)
        RUN_TEST="$RUN_TEST -show";;
    -help|--help)
        cat <<EOF
Usage: run_examples [option] kind
where
options: [defaults in brackets after descriptions]
  -makefile              (re)build makefile in test directories [default: no]
  -show                  launch DOT or VCD viewer after running the test [default: no]
  -help                  print this message
kind=dot|sim|ctask|systemc|vhdl|systemc.sim|vhdl.sim
EOF
	exit 0;;
    *) break;;
  esac
  shift
done

# echo "RUN_EXAMPLES: RUN_TEST=$RUN_TEST 1=$1"

run ()
{
nt=0
ns=0
for i in $2/{single,multi}/[a-z]*
do
  (( nt = nt + 1 ))
  $RUN_TEST $1 $i
  (( ns = ns + $? ))
done
echo "***" $ns"/"$nt "test(s) OK"
}

for i in $SUBDIRS
do
    run $1 $i
done
