RFSM=/Users/jserot/Dev/ml/rfsm/working

SRCS=div8.fsm
APP=div8
DOT_OPTS=
SIM_OPTS=
SYSTEMC_OPTS=-sc_time_unit "SC_NS" -stop_time 120
VHDL_OPTS=-vhdl_time_unit "ns" -stop_time 120

include $(RFSM)/lib/etc/Makefile.app
