#include "systemc.h"
#include "rfsm.h"
#include "inp_H.h"
#include "e.h"
#include "r.h"

int sc_main(int argc, char *argv[])
{
  sc_signal<bool> H;
  sc_signal<int> r_data;
  sc_signal<bool> e_rdy;
  sc_signal<int> v;
  sc_signal<bool> r_rdy;
  sc_signal<int> e_state;
  sc_signal<int> r_state;
  sc_trace_file *trace_file;
  trace_file = sc_create_vcd_trace_file ("main");
  sc_write_comment(trace_file, "Generated by RFSM v1.7.0 from model main.fsm");
  sc_trace(trace_file, H, "H");
  sc_trace(trace_file, r_data, "r_data");
  sc_trace(trace_file, e_rdy, "e_rdy");
  sc_trace(trace_file, v, "v");
  sc_trace(trace_file, r_rdy, "r_rdy");
  sc_trace(trace_file, e_state, "e_state");
  sc_trace(trace_file, r_state, "r_state");

  Inp_H Inp_H("Inp_H");
  Inp_H(H);

  E e("e");
  e(H,r_rdy,v,e_rdy,e_state);
  R r("r");
  r(H,e_rdy,v,r_rdy,r_data,r_state);

  sc_start(400, SC_NS);

  sc_close_vcd_trace_file (trace_file);

  return EXIT_SUCCESS;
}
