#!/bin/bash

# A script for automated testing 

RFSMMAKE=/Users/jserot/Dev/ml/rfsm/etc/bin/rfsmmake
RFSMLIB=/Users/jserot/Dev/ml/rfsm/etc

try_make ()
{
case $1 in
dot) if [ $SHOW == "yes" ]; then make dot; else make dot.run; fi;;
sim) if [ $SHOW == "yes" ]; then make sim; else make sim.run; fi;;
ctask) make ctask;;
systemc.code) make systemc.code;;
systemc.sim) make systemc.sim;;  # For comparing with simulation results
systemc) if [ $SHOW == "yes" ]; then make systemc; else make systemc.run; fi;;
vhdl.code) make vhdl.code;;
vhdl.sim) make vhdl.sim;;# For comparing with simulation results
vhdl) if [ $SHOW == "yes" ]; then make vhdl; else make vhdl.run; fi;;
all) for i in dot sim systemc vhdl;
     do
        if [ $SHOW == "yes" ]; then make $i; else make $i.run; fi
     done;;
*) false;;
esac
case $? in
0) echo "OK";;
*) echo "FAILED";;
esac
}

function run
{
echo -n "  -> making $2 in $1 ... "
(cd $1; make $2) > /dev/null 2>&1
case $? in
0) echo -e "\033[32mOK\033[0m";;
*) failed=true; echo -e "\033[31mFAILED\033[0m"; (cd $1; make $2.clobber) > /dev/null 2>&1;;
esac
}

# function check_results
# {
# echo -n "  -> checking $1 results ... "
# (cd $1; make $2.check) > /dev/null 2>&1
# case $? in
# 0)
#   echo -e "\033[32mOK\033[0m";;
# *)
#  failed=true; echo -e "\033[31m** Checking of $2 results FAILED in $1\033[0m";;
# esac
# }

function make_test 
{
    failed=false
    (cd $1; make clobber) > $TMP 2>&1
    run $1 dot 
    run $1 sim
#    check_results $1 sim
    (cd $1; make clobber) > $TMP 2>&1
}

TMP=/tmp/do_test.out

make_all ()
{
    shift
    echo "** Testing all in $1... "
    make_test $1 2>&1
    if $failed ; then
        exit 0
    else
        exit 1
    fi
}

make_makefile ()
{
    echo -n "Making Makefile in $1... "
    (cd $1; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC -o Makefile ./main.pro > $TMP 2>&1)
    grep "Wrote Makefile" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
    grep "OK" $TMP >/dev/null && exit 1
}

make_target ()
{
    if [ $CUSTOM_RFSMC == "yes" ];
    then
        echo -n "Testing $1 in $2 with RFSMC=$RFSMC... "
        (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC -o Makefile ./main.pro > $TMP 2>&1)
    else
        echo -n "Testing $1 in $2... "
    fi
    (cd $2; if [ -e Makefile ]; then make clobber > $TMP 2>&1; fi)
    (cd $2; try_make $1) > $TMP 2>&1
    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
    grep "OK" $TMP >/dev/null && exit 1
    exit 0
}

CUSTOM_RFSMC=no
SHOW=no
BUILD_MAKEF=no

while : ; do
  case "$1" in
    "") break;;
    -makefile) BUILD_MAKEF=yes;;
    -show) SHOW=yes;;
    -compiler)
        if [ -e $2 ]; then
            RFSMC=$2;
            CUSTOM_RFSMC=yes;
            shift
        else
            echo "Non existent file: $2"
            exit 1
        fi
        ;;
    -help)
        cat <<EOF
Usage: do_test [options] kind subdir
where
options: [defaults in brackets after descriptions]
  -makefile              (re)build Makefile in test directory [default: no]
  -compiler path         path to the rfsmc compiler [default: $RFSMC]
  -show                  launch DOT or VCD viewer after running the test [default: no]
  -help                  print this message
kind=makefile|dot.run|dot|sim|ctask|systemc.code|systemc.run|systemc|systemc.sim|vhdl.code|vhdl.run|vhdl|vhdl.sim
subdir=core|full|...
EOF
	exit 0;;
    *) break;;
  esac
  shift
done

IFS="/" read -ra PARTS <<< "$2"
GUEST="${PARTS[0]}"
case $GUEST in
full) ;;
*) GUEST="${PARTS[0]}/${PARTS[1]}"
esac
if [ $CUSTOM_RFSMC == "no" ]; then
    RFSMC=/Users/jserot/Dev/ml/rfsm/_build/default/src/guests/$GUEST/bin/rfsmc.bc; # Default version
fi

#echo "C=$RFSMC BUILD_MAKEF=$BUILD_MAKEF SHOW=$SHOW 1=$1 2=$2"

if [ $BUILD_MAKEF == "yes" ]; then make_makefile $2; fi
make_target $1 $2
