#!/bin/bash

RUN_TEST="../../etc/bin/run_test"

while : ; do
  case "$1" in
    "") break;;
    -makefile)
        RUN_TEST="$RUN_TEST -makefile";;
    -compiler)
        RUN_TEST="$RUN_TEST -compiler $2"; shift;;
    -help)
        cat <<EOF
Usage: run_tests [options] kind subdir
where
options: [defaults in brackets after descriptions]
  -makefile              (re)build makefile in test directories [default: no]
  -compiler path         path to the rfsmc compiler [default: $RFSMC]
  -show                  launch DOT or VCD viewer after running the test [default: no]
  -help                  print this message
kind=dot|sim|ctask|systemc|vhdl|systemc.code|vhdl.code|systemc.sim|vhdl.sim
subdir=std|others/...
EOF
	exit 0;;
    *) break;;
  esac
  shift
done

echo "RUN_TESTS: RUN_TEST=$RUN_TEST 1=$1 2=$2"

run ()
{
nt=0
ns=0
for i in $2/tests/{single,multi}/[a-z]*
do
    if [ -e $i ]; then
        (( nt = nt + 1 ))
        $RUN_TEST $1 $i
        (( ns = ns + $? ));
    fi
done
echo "***" $ns"/"$nt "test(s) OK"
}

#SUBDIRS="others/core others/simple others/szdints others/szvars std"
SUBDIRS="std"

case $2 in
    all) 
        for i in $SUBDIRS
        do
            run $1 $i
        done;;
    *)
        run $1 $2;;
esac
