#!/bin/bash

# This script is for testing that tests written for {core,simple,szdints,szvars} still compiles ok with "older" compilers 

for target in dot sim ctask systemc vhdl
do
    ./do_tests $target others/core
    for compiler in others/simple others/szdints others/szvars full
    do
         ./do_tests -compiler /Users/jserot/Dev/ml/rfsm/_build/default/src/guests/$compiler/bin/rfsmc.bc $target others/core
    done

    ./do_tests $target others/simple
    for compiler in others/szdints others/szvars full
    do
         ./do_tests -compiler /Users/jserot/Dev/ml/rfsm/_build/default/src/guests/$compiler/bin/rfsmc.bc $target others/simple
 
    done

    ./do_tests $target others/szdints
    for compiler in others/szvars full
    do
         ./do_tests -compiler /Users/jserot/Dev/ml/rfsm/_build/default/src/guests/$compiler/bin/rfsmc.bc $target others/simple
    done

    ./do_tests $target others/szvars
    for compiler in full
    do
         ./do_tests -compiler /Users/jserot/Dev/ml/rfsm/_build/default/src/guests/$compiler/bin/rfsmc.bc $target others/simple
    done

done
