#include "systemc.h"
#include "rfsm.h"
#include "inp_e.h"
#include "inp_H.h"
#include "g.h"

int sc_main(int argc, char *argv[])
{
  sc_signal<bool> e;
  sc_signal<bool> H;
  sc_signal<bool> s3;
  sc_signal<bool> s2;
  sc_signal<bool> s1;
  sc_trace_file *trace_file;
  trace_file = sc_create_vcd_trace_file ("main");
  sc_write_comment(trace_file, "Generated by RFSM v2.2");
  sc_trace(trace_file, e, "e");
  sc_trace(trace_file, H, "H");
  sc_trace(trace_file, s3, "s3");
  sc_trace(trace_file, s2, "s2");
  sc_trace(trace_file, s1, "s1");

  Inp_e Inp_e("Inp_e");
  Inp_e(e);
  Inp_H Inp_H("Inp_H");
  Inp_H(H);

  G g("g");
  g(H,e,s1);

  sc_start(100, SC_NS);

  sc_close_vcd_trace_file (trace_file);

  return EXIT_SUCCESS;
}

