RFSM=/Users/jserot/Dev/ml/rfsm/working

APP=main
DOT_OPTS=#-dot_actions_nl
SIM_OPTS=#-trace 1
SYSTEMC_OPTS=-sc_time_unit "SC_NS" -stop_time 120 
VHDL_OPTS=-vhdl_time_unit "ns" -stop_time 120 -vhdl_numeric_std

include $(RFSM)/lib/etc/Makefile.app
