TB=main

SRCS=calc.fsm main.fsm
DOT_OPTS=
SIM_OPTS=
SYSTEMC_OPTS=-sc_time_unit "SC_NS" -stop_time 120 
VHDL_OPTS=-vhdl_time_unit "ns" -stop_time 120 -vhdl_numeric_std

include ../../../lib/etc/Makefile.app
